// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvKtbcBXKbWyAS4TDUgNhdLQLgnuyKhqg',
    appId: '1:717182279221:web:29e9fd92c6824aea0e1b7c',
    messagingSenderId: '717182279221',
    projectId: 'fyp-db-81903',
    authDomain: 'fyp-db-81903.firebaseapp.com',
    storageBucket: 'fyp-db-81903.firebasestorage.app',
    measurementId: 'G-FCYWQ5SMYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMgviOmDXvqWcSTqLY2loceorjksY02r8',
    appId: '1:717182279221:android:76a17b5804e266710e1b7c',
    messagingSenderId: '717182279221',
    projectId: 'fyp-db-81903',
    storageBucket: 'fyp-db-81903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1tavgjikpwMznqPNQsaBpflJ8rL9r9XU',
    appId: '1:717182279221:ios:646a03066573e71a0e1b7c',
    messagingSenderId: '717182279221',
    projectId: 'fyp-db-81903',
    storageBucket: 'fyp-db-81903.firebasestorage.app',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1tavgjikpwMznqPNQsaBpflJ8rL9r9XU',
    appId: '1:717182279221:ios:646a03066573e71a0e1b7c',
    messagingSenderId: '717182279221',
    projectId: 'fyp-db-81903',
    storageBucket: 'fyp-db-81903.firebasestorage.app',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvKtbcBXKbWyAS4TDUgNhdLQLgnuyKhqg',
    appId: '1:717182279221:web:880ee25e4502e7660e1b7c',
    messagingSenderId: '717182279221',
    projectId: 'fyp-db-81903',
    authDomain: 'fyp-db-81903.firebaseapp.com',
    storageBucket: 'fyp-db-81903.firebasestorage.app',
    measurementId: 'G-SK8WPGG4DL',
  );
}
